### ISSUE TITLE
Buggy with Meteor 2.8.1

### ISSUE THREAD

**Issue by ebroder** [zodern/meteor-types#5]
I am not entirely sure if this is a bug in Meteor or a bug in this package, so feel free to redirect me if I have this backwards.

I attempted to upgrade my project to 2.8.1 today and take advantage of the [new embedded type declarations](https://github.com/meteor/meteor/blob/devel/docs/history.md#highlights:~:text=boundary%20by%20Grubba27-,Type%20definitions%20for%20core%20packages,-by%20piotrpospiech). However, I got an error that I was able to reproduce even on a new project:

```
evan@mathias meteor-test % meteor npx tsc --noEmit
.meteor/local/types/node_modules/package-types/meteor/package/os/packages/meteor/meteor.d.ts:3:23 - error TS2306: File '/Users/evan/src/meteor-test/.meteor/local/types/packages.d.ts' is not a module.

3 import { Blaze } from 'meteor/blaze';
                        ~~~~~~~~~~~~~~

imports/ui/Info.tsx:2:28 - error TS2306: File '/Users/evan/src/meteor-test/.meteor/local/types/packages.d.ts' is not a module.

2 import { useTracker } from 'meteor/react-meteor-data';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
```

(There are some other type errors in the Meteor TypeScript example project, but those are somewhat clearly separate)

**Comment by ebroder** [comment]
I pushed a project to https://github.com/ebroder/meteor-types-test that demonstrates the issue. All I did to create this project was:

* `meteor create --typescript .`
* `meteor add zodern:types`
* Make the requisite modifications to `tsconfig.json`
* Remove `@types/meteor` and add `@types/node`, `@types/connect`, `@types/mongo`, and `@types/underscore` (which seems like it may be a separate bug in Meteor's implementation, though I'm not entirely sure)

**Comment by zodern** [comment]
There is one more step. You need to either run the app or run `meteor lint` to generate the `packages.d.ts` file.

**Comment by ebroder** [comment]
Sorry, I should have clarified - I still see these errors even after doing that:

```
evan@mathias meteor-types-test (main) % meteor npm i
added 218 packages from 181 contributors and audited 219 packages in 1.77s

34 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

evan@mathias meteor-types-test (main) % meteor lint
   Building the application                  -
[zodern:types] Updated types
[zodern:types] Exiting "meteor lint" early
evan@mathias meteor-types-test (main) % meteor npx tsc --noEmit
.meteor/local/types/node_modules/package-types/meteor/package/os/packages/meteor/meteor.d.ts:3:23 - error TS2306: File '/Users/evan/src/meteor-types-test/.meteor/local/types/packages.d.ts' is not a module.

3 import { Blaze } from 'meteor/blaze';
                        ~~~~~~~~~~~~~~

imports/ui/Info.tsx:2:28 - error TS2306: File '/Users/evan/src/meteor-types-test/.meteor/local/types/packages.d.ts' is not a module.

2 import { useTracker } from 'meteor/react-meteor-data';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~

server/main.ts:4:29 - error TS7031: Binding element 'title' implicitly has an 'any' type.

4 async function insertLink({ title, url }) {
                              ~~~~~

server/main.ts:4:36 - error TS7031: Binding element 'url' implicitly has an 'any' type.

4 async function insertLink({ title, url }) {
                                     ~~~


Found 4 errors in 3 files.

Errors  Files
     1  .meteor/local/types/node_modules/package-types/meteor/package/os/packages/meteor/meteor.d.ts:3
     1  imports/ui/Info.tsx:2
     2  server/main.ts:4
```

**Comment by ebroder** [comment]
I'm going to go ahead and close this, as I no longer believe this is a bug in `zodern:types`. The error messages confused me, but in fact these were dependency issues - packages with invalid type declarations (https://github.com/meteor/meteor/pull/12428) or missing type declarations (https://github.com/meteor/react-packages/pull/384). But _this_ package seems to be working more or less correctly.
